### ISSUE TITLE
EP(docs): improve website

### ISSUE THREAD

**Issue by dipankardas011** [kubesimplify/ksctl#132]
# What it will bring?

```[tasklist]
### Tasks
- [x] Add new architecture
- [x] contributions guide to be merged
- [x] CI pipeline used
- [x] also make use of flags and formats of available commands
```

# Why do we need it?
To improve the website more uniform and more rich information

## Additional context

Check Contribution's guidelines
