### ISSUE TITLE
feature(kubernetes,aws,azure,civo): auto-scaling for self-managed HA clusters

### ISSUE THREAD

**Issue by dipankardas011** [kubesimplify/ksctl#174]
# Is your feature request related to a problem?📖
there is no auto-scaling of the no of nodes for HA cluster

# Describe the solution you'd like 👨‍💻👩‍💻
need a way to combine the existing ksctl-scaler docker image to tell what should be the desired no of workerplane nodes

![Image](https://github.com/kubesimplify/ksctl/assets/65275144/c5d1ca0e-3d6b-4909-b149-1e634862b161)

# Describe alternatives you've considered💠

# Provider in question
- Civo
- Azure
- K3s
- Kubeadm

## Additional context
Check [Contribution's guidelines](https://kubesimplify.github.io/ksctl/docs/contributions)

```[tasklist]
### Tasks
- [ ] https://github.com/kubesimplify/ksctl/pull/164
- [x] scale up and scale down features should always work
- [ ] all workernode deletion kubernetes workload working correctly
- [ ] able to watch any changes to any node spec
- [ ] controller to watch for metrics server for changes in resource utilization for each node and if its beyond certain threshold
- [ ] integrate the kubernetes custom controller with the ksctl http slim server
- [ ] gcr for hosting the container images
- [ ] feature flag added to cli to test working
```

**Comment by dipankardas011** [comment]
@prateek041

**Comment by dipankardas011** [comment]
.
