### ISSUE TITLE
Blog: Writing about various features ksctl provides

### ISSUE THREAD

**Issue by dipankardas011** [kubesimplify/ksctl#187]
```[tasklist]
### Tasks
- [ ] Adding the purpose
- [ ] what all challenges it resolves
- [ ] how it achieves
- [ ] what are its functionalities
- [ ] Making a pr to website/blogs/
```

**Comment by dipankardas011** [comment]
Enabled the blogging page
PR #188

**Comment by shaikahmadnawaz** [comment]
I'm interested in this, and this is my Hashnode blog https://shaikahmadnawaz.hashnode.dev

**Comment by Horiodino** [comment]
@shaikahmadnawaz  if you need any help i can :+1:

**Comment by shaikahmadnawaz** [comment]
> this is the blog https://github.com/kubesimplify/ksctl/tree/main/website/blog/2021-08-26-welcome

Sorry for asking like this; please tell me precisely what I have to write like any reference resources about ksctl @dipankardas011

**Comment by dipankardas011** [comment]
so you can check the ksctl docs (https://kubesimplify.github.io/ksctl/docs/intro)
RoadMap (https://kubesimplify.github.io/ksctl/docs/roadmap)
many more from the docs

current development is going on wrt to the UI and install applications

**Comment by dipankardas011** [comment]
feel free to ask any follow up's

**Comment by dipankardas011** [comment]
@shaikahmadnawaz are there any updates on this issue? See you soon at This Sunday's bi-weekly meeting on 15th Oct

**Comment by shaikahmadnawaz** [comment]
> @shaikahmadnawaz are there any updates on this issue? See you soon at This Sunday's bi-weekly meeting on 15th Oct

Sorry for saying this, busy with college exams, will be available in the upcoming week @dipankardas011.

**Comment by shaikahmadnawaz** [comment]
> feel free to ask any followups

Sure, I will.

**Comment by shaikahmadnawaz** [comment]
> @shaikahmadnawaz are there any updates on this issue? See you soon at This Sunday's bi-weekly meeting on 15th Oct

By the way, how can I join this meet?

**Comment by Horiodino** [comment]
> > @shaikahmadnawaz are there any updates on this issue? See you soon at This Sunday's bi-weekly meeting on 15th Oct
> 
> By the way, how can I join this meet?

you can join the kubesimplyfy discord and ksctl cnannel , see the channel pins

**Comment by dipankardas011** [comment]
> > @shaikahmadnawaz are there any updates on this issue? See you soon at This Sunday's bi-weekly meeting on 15th Oct
> 
> By the way, how can I join this meet?

https://github.com/kubesimplify/ksctl/discussions/207

**Comment by saiyam1814** [comment]
@shaikahmadnawaz have you started working on this blog yet? we want to get this out so please confirm is you have already started working.

**Comment by shaikahmadnawaz** [comment]
> @shaikahmadnawaz have you started working on this blog yet? we want to get this out so please confirm is you have already started working. 

I'm not able to understand what to write, I mean the table of contents or topics I need to write, can you please help. @saiyam1814

**Comment by dipankardas011** [comment]
@shaikahmadnawaz as we have migrated the docs website to a new repo you can work on this issue https://github.com/kubesimplify/ksctl-docs/issues/1

**Comment by shaikahmadnawaz** [comment]
> @shaikahmadnawaz as we have migrated the docs website to a new repo you can work on this issue https://github.com/kubesimplify/ksctl-docs/issues/1

Okay 👍🏻
