### ISSUE TITLE
enhancement(core): Ksctl project refactoring

### ISSUE THREAD

**Issue by dipankardas011** [kubesimplify/ksctl#189]
# Why do we need it?
If anyone wants to refer the coding standards aka project naming structure
Here is a good reference https://github.com/golang-standards/project-layout

# What it will bring?
this issue tries to resolve the current project structure
I think the api/ folder in root should be renamed with https://github.com/golang-standards/project-layout#internal or pkg/ not sure would love to discussion regarding it

```[tasklist]
### Tasks
- [x] deciding which name should be followed (Ans. as api is used for openapi or swaggerui)
- [x] what should be the internal structure
- [x] refactor the go.mod and import statements
- [x] unit test
- [x] documentation
- [x] e2e-test refactoring
- [x] overall refactoring
```

## Additional context
you can should resolve them in seperate PR's and this Issue should link to the specific branch which is already linked with this branch

Check [Contribution's guidelines](https://kubesimplify.github.io/ksctl/docs/contributions)
