### ISSUE TITLE
feature(UI): Support for ksctl UI

### ISSUE THREAD

**Issue by dipankardas011** [kubesimplify/ksctl#191]
# Is your feature request related to a problem?📖
another option to interact with the ksctl core to do specific task

# Describe the solution you'd like 👨‍💻👩‍💻

> **Note**
Currently in Discussion phase

HTTP streams needed for ksctl core to share with the frontend
make the cli and the frontend indenendent [Point Of Discuss]

```[tasklist]
### Tasks
- [ ] Seperation of Logger and Storage interfaces
- [ ] Add Global Const Error (_OPTIONAL_)
- [ ] for generating what should be the API endpoints look like https://editor.swagger.io/
- [ ] https://github.com/kubesimplify/ksctl/issues/229
- [ ] whether to create the server in websocket or HTTP
```

# Describe alternatives you've considered💠

# Provider in question
- Ksctl core

## Additional context
Check [Contribution's guidelines](https://kubesimplify.github.io/ksctl/docs/contributions)

**Comment by dipankardas011** [comment]
We will be using http streams (ksctl dashboard)
- The logger will write on specific format during stream events like
```go
type ServerResponse struct {
  Msg string, 
  IsError bool, 
  Error string,
}
```
- Openapi spec need to be defined for the server
- The backend will contain auth, authorization based execute functionality
- Dashboard is just a Web UI format
- Single ksctl server and multiple users to use with username and password will be our first approach
- seperate the logger and the storage
