### ISSUE TITLE
feature: Improve the `storageFactory` and MongoDB

### ISSUE THREAD

**Issue by dipankardas011** [kubesimplify/ksctl#226]
# Why do we need it?
It needs some review on what all methods needs to be there?
and also what all implementer needs to be added

# What it will bring?

```[tasklist]
### Tasks
- [ ] #193
- [x] review of the `StorageFactory`
- [x] added mongodb support with file based routing such that it sould behave just like we do file based traversal and RW
- [x] check how to create ssh keypairs without `ssh-keygen` cli command
- [ ] https://github.com/kubesimplify/ksctl/issues/229
- [ ] Add the implementation
```

## Additional context

Check [Contribution's guidelines](https://kubesimplify.github.io/ksctl/docs/contributions)

**Comment by dipankardas011** [comment]
# From the meeting notes
we must added an extra field when storing the stateConfiguration data


## Azure
https://github.com/kubesimplify/ksctl/blob/3a122382579d7aa020cd5ed0cb161070752d49ab/internal/cloudproviders/azure/main.go#L46-L73

## Civo
https://github.com/kubesimplify/ksctl/blob/3a122382579d7aa020cd5ed0cb161070752d49ab/internal/cloudproviders/civo/main.go#L50-L71

## Local
https://github.com/kubesimplify/ksctl/blob/3a122382579d7aa020cd5ed0cb161070752d49ab/internal/cloudproviders/local/main.go#L17-L22


do
```diff
type StateConfiguration struct {
    ...
+   ClusterType string `json:"cluster_type"`
    ...
}
```

so that we can do search operation using `ClusterName`, `Region`, `ClusterType` fields as a composite key to get if the cluster already exist or not

**Comment by dipankardas011** [comment]
For Local provider we can only check for `clusterName` and `clusterType` as region is not applicable

i know that clusterType doesn't make sense as we only support Managed by kind but the core of local provider is build using the clusterType as managed so we will see if its better to keep or only check for the clustername for local provider

**Comment by dipankardas011** [comment]
@prateek041, From my end this POC #252 is almost done
so next we will be completing the implementation

**Comment by dipankardas011** [comment]
Can you check and tell
