### ISSUE TITLE
enhacement: replace the dep of `ssh-keygen` with golang pkg

### ISSUE THREAD

**Issue by dipankardas011** [kubesimplify/ksctl#229]
```[tasklist]
### Tasks
- [x] find the ssh library
- [x] Create a temp replacement function
- [ ] do real world compatability
```

**Comment by dipankardas011** [comment]
Found this https://gist.github.com/devinodaniel/8f9b8a4f31573f428f29ec0e884e6673
